load("@rules_cc//cc:defs.bzl","cc_binary","cc_library")

cc_library(
    name = "module_if",
    hdrs = ["module_if.h"],
    deps = ["//platform/defines:platform_def"],
    visibility = ["//visibility:public"],
)