load("@rules_cc//cc:defs.bzl","cc_binary","cc_library")

cc_binary(
    name = "fully_asso_cache_test",
    srcs = ["fully_asso_cache_test.cc"],
    deps = [
        "//platform/core/cache:fully_asso_cache"
    ],
    visibility=["//visibility:public"]
)
