load("@rules_cc//cc:defs.bzl","cc_binary","cc_library")

cc_library(
    name = "rmu_if",
    srcs = [glob("*.h")],
    deps = ["//platform/defines:platform_def"],
    visibility = ["//visibility:public"],
)